Fix setup
OpenUpSA/khetha-django pull request #33
Opened 2019-06-04 06:10 UTC by jbothma

2019-06-04 10:35 UTC, PiDelport requested changes

2019-06-04 10:35 UTC, PiDelport commented on docker-compose.yml
> -    command: 'django-admin runserver --nostatic 0.0.0.0:8000'
WhiteNoise requires `--nostatic` to work with `runserver`:

http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development

2019-06-04 16:04 UTC, merged

2019-06-04 16:08 UTC, PiDelport commented on README.md
> +docker-compose run --rm web django-admin loaddata /root/.local/lib/python3.7/site-packages/khetha/fixtures/sample-task-data.json
Note that `loaddata sample-task-data` suffices here: the file path is not needed.

(Django automatically discovers fixtures in each app's `fixtures` directory.)

2019-06-05 13:43 UTC, jbothma commented
Ah brilliant - thanks! Will patch next time I touch

On Tue, 4 Jun 2019 at 18:08, Pi Delport <notifications@github.com> wrote:

> *@PiDelport* commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/OpenUpSA/khetha-django/pull/33#discussion_r290377739>:
>
> >
>  ```
>  docker-compose up
>  ```
>
> +Set up database tables first time you set up the database
> +
> +```
> +docker-compose run --rm web django-admin migrate
> +docker-compose run --rm web django-admin createsuperuser
> +```
> +
> +Load some development data
> +
> +```
> +docker-compose run --rm web django-admin loaddata /root/.local/lib/python3.7/site-packages/khetha/fixtures/sample-task-data.json
>
> Note that loaddata sample-task-data suffices here: the file path is not
> needed.
>
> (Django automatically discovers fixtures in each app's fixtures
> directory.)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenUpSA/khetha-django/pull/33?email_source=notifications&email_token=AABZSGPN6HNRTV73TP5PXF3PY2HRNA5CNFSM4HSZCEU2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB2RNARQ#pullrequestreview-245551174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABZSGL6O2PFB2WM6VL3WGTPY2HRNANCNFSM4HSZCEUQ>
> .
>